### ISSUE TITLE
individual opacity based on contrib or cos2 for FactoMiner::PCA objects

### ISSUE THREAD

**Issue by ginolhac** [juba/explor#13]
As promised I tried `explor` and was very happy with it!
May I suggest to add the transparency control for individuals based on their contribution / cos2 in the same way as for variables?

Thanks again for developing such a nice package.

**Comment by juba** [comment]
You mean add a way to change opacity depending on contrib/cos2 for individuals, in the same way the size can change for variables ?

Yes, that could be possible...

**Comment by ginolhac** [comment]
Yes. But I am wondering if this is not redundant with Factoshiny. The overlap is in between.

**Comment by juba** [comment]
I'm not sure to get what you mean by this ?

**Comment by ginolhac** [comment]
I meant that would be nice, but don't put it high priority as I can use Factoshiny. I do prefer your interface but I can get the functionality elsewhere when needed

**Comment by juba** [comment]
Ok, thanks for the clarification ! 

I may not work on it really soon, but I think it could make a nice addition, so keeping the issue open...

**Comment by juba** [comment]
Finally I worked a bit on it today and implemented the feature for PCA and MCA on the development version : 

```r
devtools::install_github("juba/explor")
```

Could you please let me know what you think of it when you have the time ?

**Comment by ginolhac** [comment]
waou! that was fast ;)

works well, thanks a lot. Maybe some improvements could be:

- labels opacity being synchronized to the dot ones. Right now, if set on, they overlay the nice transparency of dots.
- choose to display labels / dots based on a certain value of contrib / cos2. It sounds like it deserve a separate issue, but just a suggestion.

**Comment by juba** [comment]
Yes, hiding labels based on a certain threshold would be useful. It's already available for variables, by the way. I'll look into that.

**Comment by juba** [comment]
Hi, sorry it has been quite a long time since I worked on this issue, but today I implemented the ability to hide individuals points labels based on their contribution.

So regarding your original request, labels are still of constant opacity (the idea behind is that if you display a label it is for it to be readable, so a show/hide mechanism seems better than an opacity one), and it's only possible to filter labels based on contribution, not on Cos2. The latter is definitely possible, but I fear it would make the interface even clunkier than it is now.

Sorry for the long delay, and please let me know what you think !

**Comment by juba** [comment]
Closing it for now.

**Comment by ginolhac** [comment]
thanks for the enhancement, and sorry for the delay. I am happy with your recent addition, that's great.
